# Generated by Django 6.0.5 on 2026-05-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='difficulty',
            field=models.CharField(default='Fresher', max_length=100),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='keywords',
            field=models.JSONField(default=list),
        ),
    ]
