# Generated by Django 6.0.5 on 2026-05-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_questionbank_category_questionbank_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question',
            field=models.TextField(),
        ),
    ]
